const types = {
    PLAY_SONG: 'PLAY_SONG',
    SET_PLAYING: 'SET_PLAYING',
    SET_PAUSE: 'SET_PAUSE',
    SET_STOP: 'SET_STOP',
    SET_CURRENT_TIME: 'SET_CURRENT_TIME',
    SET_DURATION: 'SET_DURATION',
    SET_CURRENT_SONG: 'SET_CURRENT_SONG',
    SEEK_POSITION: 'SEEK_POSITION',
};
export default types;
